/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as test from "./test";
export type { test };
export type { Auction1 } from "./Auction1";
export type { Lock } from "./Lock";
export type { MyToken } from "./MyToken";
export type { NftAuction } from "./NftAuction";
export type { NftAuctionV2 } from "./NftAuctionV2";
